# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLWZ_6PQX5T9vliRH3KInx_6zzxgVL03
"""

import nltk
import numpy as np
import random
import string

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')

corpus =  """
Artificial Intelligence is used in real life for chatbots, recommendation systems, voice assistants, and fraud detection.
Machine learning helps systems improve automatically by learning patterns from data.
In real-time applications, machine learning models are used for predictions, classification, and personalization.
Supervised learning uses labeled datasets to train models for tasks like spam detection and sentiment analysis.
Unsupervised learning is used in real-world applications like customer segmentation and anomaly detection.
Reinforcement learning is used in robotics, gaming, and self-driving cars.
Overfitting occurs when a model memorizes training data and fails to generalize to unseen data.
Underfitting happens when a model is too simple to capture patterns in data.
Python is widely used in AI and machine learning because of libraries like NumPy, Pandas, Scikit-learn, and TensorFlow.
Natural Language Processing enables machines to understand and respond to human language.
Chatbots use NLP techniques to process user queries and generate meaningful responses.
Recommendation systems suggest products or content based on user behavior and preferences.
Computer vision is used in facial recognition, medical image analysis, and autonomous vehicles.
Data preprocessing includes cleaning, normalization, and feature extraction to improve model performance.
Model evaluation metrics include accuracy, precision, recall, and F1-score.
Machine learning models are deployed in real-time using APIs and cloud platforms.
Ethical AI focuses on fairness, transparency, and responsible use of artificial intelligence.
AI is widely used in healthcare for disease prediction, diagnosis, and patient monitoring.
In finance, AI is used for fraud detection, credit scoring, and algorithmic trading.
AI-powered virtual assistants help users with scheduling, customer support, and information retrieval.
"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

sent_tokens = corpus.split(".")

def chatbot_response(user_input):
    sent_tokens.append(user_input)

    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(sent_tokens)

    similarity = cosine_similarity(tfidf_matrix[-1], tfidf_matrix)
    idx = similarity.argsort()[0][-2]
    score = similarity[0][idx]

    sent_tokens.pop()

    if score == 0:
        return "Sorry, I didn't understand that. Can you rephrase?"
    else:
        return sent_tokens[idx]

print("🤖 AIML Chatbot (type 'exit' to stop)\n")

while True:
    user_text = input("You: ")

    if user_text.lower() == "exit":
        print("Bot: Goodbye 👋")
        break

    print("Bot:", chatbot_response(user_text))

